--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/EntityMonitor
build-by-default: true
branches:
- master
- "legacy/PM3"
projects:
  EntityMonitor:
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando # Temporary until the original updates
        version: ^3.2.0
        branch: PM5
...
