--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/EntityMonitor
build-by-default: true
branches:
- master
- "legacy/PM3"
projects:
  EntityMonitor:
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.1.0
...
