name: EntityMonitor
main: JavierLeon9966\EntityMonitor\EntityMonitor
author: JavierLeon9966
version: 2.3.0
api: 5.0.0
mcpro-protocols: [594, 618, 622]
description: Plugin that monitors every chunk for potential amount of entities and tiles
website: https://github.com/JavierLeon9966/EntityMonitor
permissions:
  entitymonitor.command.monitor.entity:
    description: Allows the user to monitor worlds with most entities
    default: op
  entitymonitor.command.monitor.tile:
    description: Allows the user to monitor worlds with most tiles
    default: op